### ISSUE TITLE
서비스 피드백 3가지가 있습니다

### ISSUE THREAD

**Issue by orot-shindonghwi** [donghyeun02/schedule-helper#66]
![image](https://github.com/donghyeun02/schedule-helper/assets/109847226/fd16350d-4f77-426c-8b0b-70f5bb6210f8)

1. (종일) - 배동희 연차라고 표시되면 좋을거 같습니다.

2. 종일 알림에 대해서는 리마인드를 안울려도 될 것 같습니다.

3. 15분전 리마인드 알림이 울리는 시간이 잘못된거같습니다

**Comment by donghyeun02** [comment]
### 이슈 해결 :

- **15분 전 리마인드 알림 수정:**
  - 15분 전 알림이 정상적으로 동작하도록 수정했습니다.
  - 해당 기능은 9시부터 23시까지 작동하며 종일 일정에 대한 알림이 울리지 않도록 조정되었습니다.

**Comment by orot-shindonghwi** [comment]
👍
