### ISSUE TITLE
메세지 포맷 변경해주세요

### ISSUE THREAD

**Issue by orot-shindonghwi** [donghyeun02/schedule-helper#67]
<img width="270" alt="스크린샷 2024-01-31 오전 10 09 47" src="https://github.com/donghyeun02/schedule-helper/assets/109847226/4bcecbd8-1562-4cd4-a82b-29e4e26d2586">

"당일 일정이 없습니다" => "오늘 일정이 없습니다"

그리고 오른쪽에 보이는 Assignees랑 Labels 생성해주세요

**Comment by donghyeun02** [comment]
### 이슈 해결 :

- **리마인더 메시지 포멧 변경:**
  - 당일 일정이 없을 경우의 메시지 포멧을 "당일 일정이 없습니다" => "오늘 일정이 없습니다"로 변경하였습니다.
